spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

cs:
  rabbitmq:
    exchange: cs.exchange.message
    queue:
      main:
        name: cs.queue.message
      retry:
        name: cs.queue.message.retry
        delay-in-ms: 1000
        limit: 10
      unprocessed:
        name: cs.queue.message.unprocessed
    routing-key: cs.routing-key.message

server:
  port: 9090